export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_GENRES = "GET_GENRES";

export const GET_VIDEOS = "GET_VIDEOS";
export const FILTER_VIDEOS_BY_GENRE = "FILTER_VIDEOS_BY_GENRE";
export const FILTER_VIDEOS_BY_MULTIPLE_GENRE = "FILTER_VIDEOS_BY_MULTIPLE_GENRE";
export const FILTER_VIDEOS_BY_NAME = "FILTER_VIDEOS_BY_NAME";